package appdefaults

import "time"

const (
	DefaultSiteName                           = "MySSO"
	DefaultFirstPartyClientID                 = "demo-client"
	DefaultFirstPartyScope                    = "openid profile email gateway.read"
	FirstPartyClientOwnerID                   = "system"
	FirstPartyWebPortalName                   = "First-Party Web Portal"
	FirstPartyWebPortalDescription            = "Built-in first-party web client for the MySSO login portal."
	DefaultLoginCodeSubjectTemplate           = "MySSO 登录验证码"
	DefaultLoginCodeBodyTemplate              = "你好，\n\n你的登录验证码是 {{code}} ，{{minutes}} 分钟内有效。\n\n邮箱：{{email}}\n\n如果这不是你的操作，请忽略此邮件。"
	DefaultLoginCodeSubjectTemplateEN         = "MySSO Login Verification Code"
	DefaultLoginCodeBodyTemplateEN            = "Hello,\n\nYour login verification code is {{code}}. It is valid for {{minutes}} minutes.\n\nEmail: {{email}}\n\nIf this was not you, please ignore this email."
	DefaultRegisterCodeSubjectTemplate        = "MySSO 注册验证码"
	DefaultRegisterCodeBodyTemplate           = "你好，\n\n你的注册验证码是 {{code}} ，{{minutes}} 分钟内有效。\n\n邮箱：{{email}}\n国家：{{country}}\n\n如果这不是你的操作，请忽略此邮件。"
	DefaultRegisterCodeSubjectTemplateEN      = "MySSO Registration Verification Code"
	DefaultRegisterCodeBodyTemplateEN         = "Hello,\n\nYour registration verification code is {{code}}. It is valid for {{minutes}} minutes.\n\nEmail: {{email}}\nCountry/Region: {{country}}\n\nIf this was not you, please ignore this email."
	DefaultResetPasswordCodeSubjectTemplate   = "MySSO 找回密码验证码"
	DefaultResetPasswordCodeBodyTemplate      = "你好，\n\n你正在通过邮箱验证码重置 MySSO 账号密码，验证码是 {{code}} ，{{minutes}} 分钟内有效。\n\n邮箱：{{email}}\n\n如果这不是你的操作，请忽略此邮件。"
	DefaultResetPasswordCodeSubjectTemplateEN = "MySSO Password Reset Verification Code"
	DefaultResetPasswordCodeBodyTemplateEN    = "Hello,\n\nYou are resetting the password for your MySSO account by email verification code. Your code is {{code}} and it is valid for {{minutes}} minutes.\n\nEmail: {{email}}\n\nIf this was not you, please ignore this email."
	DefaultDeleteAccountCodeSubjectTemplate   = "MySSO 账号注销验证码"
	DefaultDeleteAccountCodeBodyTemplate      = "你好，\n\n你正在申请注销 MySSO 账号，验证码是 {{code}} ，{{minutes}} 分钟内有效。\n\n账号邮箱：{{email}}\n\n如果这不是你的操作，请立即检查账号安全。"
	DefaultDeleteAccountCodeSubjectTemplateEN = "MySSO Account Deletion Verification Code"
	DefaultDeleteAccountCodeBodyTemplateEN    = "Hello,\n\nYou are requesting deletion of your MySSO account. Your verification code is {{code}} and it is valid for {{minutes}} minutes.\n\nAccount email: {{email}}\n\nIf this was not you, please review your account security immediately."
	DefaultChangeEmailCodeSubjectTemplate     = "MySSO 邮箱变更验证码"
	DefaultChangeEmailCodeBodyTemplate        = "你好，\n\n你正在修改 MySSO 账号绑定邮箱，验证码是 {{code}} ，{{minutes}} 分钟内有效。\n\n新邮箱：{{email}}\n\n如果这不是你的操作，请忽略此邮件。"
	DefaultChangeEmailCodeSubjectTemplateEN   = "MySSO Email Change Verification Code"
	DefaultChangeEmailCodeBodyTemplateEN      = "Hello,\n\nYou are changing the email address bound to your MySSO account. Your verification code is {{code}} and it is valid for {{minutes}} minutes.\n\nNew email: {{email}}\n\nIf this was not you, please ignore this email."
	DefaultVerificationCodeCooldownSeconds    = 60
	DefaultVerificationCodeTTLMinutes         = 10
	DefaultEmailVerificationCodeDailyLimit    = 0
	DefaultSMSVerificationCodeDailyLimit      = 0
	DefaultCaptchaEnabled                     = false
	DefaultCaptchaHeight                      = 60
	DefaultCaptchaWidth                       = 240
	DefaultCaptchaMode                        = 3
	DefaultCaptchaComplexOfNoiseText          = 0
	DefaultCaptchaComplexOfNoiseDot           = 0
	DefaultCaptchaIsShowHollowLine            = false
	DefaultCaptchaIsShowNoiseDot              = true
	DefaultCaptchaIsShowNoiseText             = false
	DefaultCaptchaIsShowSlimeLine             = true
	DefaultCaptchaIsShowSineLine              = false
	DefaultCaptchaLength                      = 6
	DefaultCaptchaTTLSeconds                  = 300
	DefaultCaptchaImageRateLimitPerMinute     = 60
	DefaultCaptchaPrecheckRateLimitPerMinute  = 120
	DefaultCaptchaTargetRateLimitPerMinute    = 20
	MaxCaptchaRateLimitPerMinute              = 10000
	DefaultSMTPPort                           = "587"
	DefaultSMSProvider                        = "disabled"
	DefaultSMSTemplateProvider                = "disabled"
	DefaultSMSAPIBase                         = "http://api.smsbao.com/"
	DefaultSMSSignature                       = ""
	DefaultSMSLoginTemplate                   = "【{{signature}}】你的登录验证码是 {{code}}，{{minutes}} 分钟内有效。"
	DefaultSMSRegisterTemplate                = "【{{signature}}】你的验证码是 {{code}}，{{minutes}} 分钟内有效。"
	DefaultSMSResetPasswordTemplate           = "【{{signature}}】你正在重置密码，验证码是 {{code}}，{{minutes}} 分钟内有效。"
	DefaultSMSBindPhoneTemplate               = "【{{signature}}】你正在绑定手机号，验证码是 {{code}}，{{minutes}} 分钟内有效。"
	DefaultSMSDeleteAccountTemplate           = "【{{signature}}】你正在申请注销账号，验证码是 {{code}}，{{minutes}} 分钟内有效。"
	DefaultAliyunSMSEndpoint                  = "dypnsapi.aliyuncs.com"
	DefaultAliyunSMSRegionID                  = "cn-hangzhou"
	DefaultAliyunSMSSignName                  = ""
	DefaultAliyunSMSLoginTemplateCode         = ""
	DefaultAliyunSMSRegisterTemplateCode      = ""
	DefaultAliyunSMSResetTemplateCode         = ""
	DefaultAliyunSMSBindPhoneTemplateCode     = ""
	DefaultAliyunSMSDeleteTemplateCode        = ""
	DefaultPublicBaseURL                      = "http://localhost:8080"
	DefaultFrontendBaseURL                    = "http://localhost:5173"
	DefaultSiteLogoDataURL                    = ""
	DefaultSiteICPRecordNumber                = ""
	DefaultSitePublicSecurityRecordNumber     = ""
	DefaultAllowUserRegistration              = true
	DefaultHomePageAnnouncementEnabled        = false
	DefaultHomePageAnnouncementContent        = ""
	DefaultUserCenterAnnouncementEnabled      = false
	DefaultUserCenterAnnouncementContent      = ""
	DefaultDeveloperAnnouncementEnabled       = false
	DefaultDeveloperAnnouncementContent       = ""
	DefaultOIDCAutoApproveClientIDs           = ""
	DefaultOIDCAutoApproveRedirectHosts       = ""
	DefaultSMTPVerificationCodeCooldownText   = "60"
	DefaultRiskControlEnabled                 = false
	DefaultRiskImmediateBindProbability       = 50
	DefaultRiskDelayedBindProbability         = 50
	DefaultRiskDelayedBindLoginCount          = 3
	DefaultDeveloperManagedUsersSearchWindow  = 10
	DefaultDeveloperManagedUsersSearchLimit   = 5
	MaxDeveloperManagedUsersSearchWindow      = 3600
	MaxDeveloperManagedUsersSearchLimit       = 10000
	MaxVerificationCodeDailyLimit             = 100000
	DefaultTestSMSContentMaxLength            = 500
)

var AccountDeletionGracePeriod = 7 * 24 * time.Hour
